server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.simflow$ {
        default_type text/plain;
        add_header Cache-Control "no-cache";
    }

    location ~* \.(js|mjs)$ {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/plain text/css text/javascript application/json image/svg+xml;
}
